id: https://example.com/GISAID
name: GISAID
description: ''
version: 1.0.2
imports:
- linkml:types
prefixes:
  linkml: https://w3id.org/linkml/
  GENEPIO: http://purl.obolibrary.org/obo/GENEPIO_
classes:
  dh_interface:
    name: dh_interface
    description: A DataHarmonizer interface
    from_schema: https://example.com/GISAID
  GISAID:
    name: GISAID
    description: Specification for GISAID virus biosample data gathering
    is_a: dh_interface
    slots:
    - submitter
    - fasta_filename
    - virus_name
    - type
    - passage_details_history
    - collection_date
    - location
    - additional_location_information
    - host
    - additional_host_information
    - sampling_strategy
    - gender
    - patient_age
    - patient_status
    - specimen_source
    - outbreak
    - last_vaccinated
    - treatment
    - sequencing_technology
    - assembly_method
    - coverage
    - originating_lab
    - address
    - sample_id_given_by_the_sample_provider
    - submitting_lab
    - address
    - sample_id_given_by_the_submitting_laboratory
    - authors
    slot_usage:
      submitter:
        rank: 1
        slot_group: GISAID Submission Form
      fasta_filename:
        rank: 2
        slot_group: GISAID Submission Form
      virus_name:
        rank: 3
        slot_group: GISAID Submission Form
      type:
        rank: 4
        slot_group: GISAID Submission Form
      passage_details_history:
        rank: 5
        slot_group: GISAID Submission Form
      collection_date:
        rank: 6
        slot_group: GISAID Submission Form
      location:
        rank: 7
        slot_group: GISAID Submission Form
      additional_location_information:
        rank: 8
        slot_group: GISAID Submission Form
      host:
        rank: 9
        slot_group: GISAID Submission Form
      additional_host_information:
        rank: 10
        slot_group: GISAID Submission Form
      sampling_strategy:
        rank: 11
        slot_group: GISAID Submission Form
      gender:
        rank: 12
        slot_group: GISAID Submission Form
      patient_age:
        rank: 13
        slot_group: GISAID Submission Form
      patient_status:
        rank: 14
        slot_group: GISAID Submission Form
      specimen_source:
        rank: 15
        slot_group: GISAID Submission Form
      outbreak:
        rank: 16
        slot_group: GISAID Submission Form
      last_vaccinated:
        rank: 17
        slot_group: GISAID Submission Form
      treatment:
        rank: 18
        slot_group: GISAID Submission Form
      sequencing_technology:
        rank: 19
        slot_group: GISAID Submission Form
      assembly_method:
        rank: 20
        slot_group: GISAID Submission Form
      coverage:
        rank: 21
        slot_group: GISAID Submission Form
      originating_lab:
        rank: 22
        slot_group: GISAID Submission Form
      address:
        rank: 26
        slot_group: GISAID Submission Form
      sample_id_given_by_the_sample_provider:
        rank: 24
        slot_group: GISAID Submission Form
      submitting_lab:
        rank: 25
        slot_group: GISAID Submission Form
      sample_id_given_by_the_submitting_laboratory:
        rank: 27
        slot_group: GISAID Submission Form
      authors:
        rank: 28
        slot_group: GISAID Submission Form
slots:
  submitter:
    name: submitter
    title: Submitter
    description: enter your GISAID-Username
    range: WhitespaceMinimizedString
    required: true
  fasta_filename:
    name: fasta_filename
    title: FASTA filename
    description: the filename that contains the sequence without path (e.g. all_sequences.fasta
      not c:\users\meier\docs\all_sequences.fasta)
    range: WhitespaceMinimizedString
    required: true
  virus_name:
    name: virus_name
    title: Virus name
    description: e.g. hCoV-19/Netherlands/Gelderland-01/2020 (Must be FASTA-Header
      from the FASTA file all_sequences.fasta)
    range: WhitespaceMinimizedString
    required: true
  type:
    name: type
    title: Type
    description: default must remain "betacoronavirus"
    range: TypeMenu
    required: true
  passage_details_history:
    name: passage_details_history
    title: Passage details/history
    description: e.g. Original, Vero
    range: WhitespaceMinimizedString
    required: true
  collection_date:
    name: collection_date
    title: Collection date
    description: Date in the format YYYY or YYYY-MM or YYYY-MM-DD
    range: WhitespaceMinimizedString
    required: true
  location:
    name: location
    title: Location
    description: e.g. Europe / Germany / Bavaria / Munich
    range: WhitespaceMinimizedString
    required: true
  additional_location_information:
    name: additional_location_information
    title: Additional location information
    description: e.g. Cruise Ship, Convention, Live animal market
    range: WhitespaceMinimizedString
  host:
    name: host
    title: Host
    description: e.g. Human, Environment, Canine, Manis javanica, Rhinolophus affinis,
      etc
    range: WhitespaceMinimizedString
    required: true
  additional_host_information:
    name: additional_host_information
    title: Additional host information
    description: "e.g. Patient infected while traveling in \u2026."
    range: WhitespaceMinimizedString
  sampling_strategy:
    name: sampling_strategy
    title: Sampling Strategy
    description: e.g. Sentinel surveillance (ILI), Sentinel surveillance (ARI), Sentinel
      surveillance (SARI), Non-sentinel-surveillance (hospital), Non-sentinel-surveillance
      (GP network), Longitudinal sampling on same patient(s), S gene dropout
    range: WhitespaceMinimizedString
  gender:
    name: gender
    title: Gender
    description: Male, Female, or unknown
    range: WhitespaceMinimizedString
    required: true
  patient_age:
    name: patient_age
    title: Patient age
    description: e.g.  65 or 7 months, or unknown
    range: WhitespaceMinimizedString
    required: true
  patient_status:
    name: patient_status
    title: Patient status
    description: e.g.  Hospitalized, Released, Live, Deceased, or unknown
    range: WhitespaceMinimizedString
    required: true
  specimen_source:
    name: specimen_source
    title: Specimen source
    description: e.g. Sputum, Alveolar lavage fluid, Oro-pharyngeal swab, Blood, Tracheal
      swab, Urine, Stool, Cloakal swab, Organ, Feces, Other
    range: WhitespaceMinimizedString
  outbreak:
    name: outbreak
    title: Outbreak
    description: Date, Location e.g. type of gathering, Family cluster, etc.
    range: WhitespaceMinimizedString
  last_vaccinated:
    name: last_vaccinated
    title: Last vaccinated
    description: provide details if applicable
    range: WhitespaceMinimizedString
  treatment:
    name: treatment
    title: Treatment
    description: Include drug name, dosage
    range: WhitespaceMinimizedString
  sequencing_technology:
    name: sequencing_technology
    title: Sequencing technology
    description: e.g.  Illumina Miseq, Sanger, Nanopore MinION, Ion Torrent, etc.
    range: WhitespaceMinimizedString
    required: true
  assembly_method:
    name: assembly_method
    title: Assembly method
    description: e.g. CLC Genomics Workbench 12, Geneious 10.2.4, SPAdes/MEGAHIT v1.2.9,
      UGENE v. 33, etc.
    range: WhitespaceMinimizedString
  coverage:
    name: coverage
    title: Coverage
    description: e.g. 70x, 1,000x, 10,000x (average)
    range: WhitespaceMinimizedString
  originating_lab:
    name: originating_lab
    title: Originating lab
    description: Where the clinical specimen or virus isolate was first obtained
    range: WhitespaceMinimizedString
    required: true
  address:
    name: address
    title: Address
    range: WhitespaceMinimizedString
    required: true
  sample_id_given_by_the_sample_provider:
    name: sample_id_given_by_the_sample_provider
    title: Sample ID given by the sample provider
    range: WhitespaceMinimizedString
  submitting_lab:
    name: submitting_lab
    title: Submitting lab
    description: Where sequence data have been generated and submitted to GISAID
    range: WhitespaceMinimizedString
    required: true
  sample_id_given_by_the_submitting_laboratory:
    name: sample_id_given_by_the_submitting_laboratory
    title: Sample ID given by the submitting laboratory
    range: WhitespaceMinimizedString
  authors:
    name: authors
    title: Authors
    description: a comma separated list of Authors with complete First followed by
      Last Name
    range: WhitespaceMinimizedString
enums:
  TypeMenu:
    name: TypeMenu
    title: Type menu
    permissible_values:
      betacoronavirus:
        text: betacoronavirus
types:
  WhitespaceMinimizedString:
    name: WhitespaceMinimizedString
    typeof: string
    description: 'A string that has all whitespace trimmed off of beginning and end,
      and all internal whitespace segments reduced to single spaces. Whitespace includes
      #x9 (tab), #xA (linefeed), and #xD (carriage return).'
    base: str
    uri: xsd:token
  Provenance:
    name: Provenance
    typeof: string
    description: A field containing a DataHarmonizer versioning marker. It is issued
      by DataHarmonizer when validation is applied to a given row of data.
    base: str
    uri: xsd:token
settings:
  Title_Case: (((?<=\b)[^a-z\W]\w*?|[\W])+)
  UPPER_CASE: '[A-Z\W\d_]*'
  lower_case: '[a-z\W\d_]*'
